import torch

def get_grid(x, L):
    """
    Generates a grid of spatial coordinates scaled by L.
    
    If L is a float or int, the grid is generated by linearly spacing from 0 to L
    for each sample in the batch. If L is a tensor of shape [B] (or [B, 1]),
    then each sample's grid is generated using its corresponding L value.
    
    Args:
        x: a tensor of shape (B, D, T_in); here, only D (spatial dimension) is used.
        L: a scalar (float/int) or tensor of shape (B,) indicating the scaling factor.
    
    Returns:
        A tensor of shape (B, D, 1) containing the grid.
    """
    B, D = x.shape[:2]
    
    if isinstance(L, (float, int)):
        # Create a grid from 0 to L for D points and repeat it for each sample in the batch.
        grid = torch.linspace(0, L, steps=D, dtype=x.dtype, device=x.device)
        grid = grid.view(1, D, 1).repeat(B, 1, 1)
    elif isinstance(L, torch.Tensor):
        # Ensure L is of shape (B, 1, 1) for broadcasting.
        L = L.view(B, 1, 1)
        # Create a base grid from 0 to 1, then scale it by L for each batch.
        base = torch.linspace(0, 1, steps=D, dtype=x.dtype, device=x.device)
        grid = L * base.view(1, D, 1)
    else:
        raise ValueError("L must be a float, int, or a torch.Tensor")
    
    return grid
